### ISSUE TITLE
uninitialized constant DatabaseCleaner

### ISSUE THREAD

**Issue by K-Sato1995** [K-Sato1995/blog_backend#16]
```
error occurred while loading ./spec/requests/api/v1/posts_controller_spec.rb.
Failure/Error: add_grpup 'API', 'app/controllers/api/'

NoMethodError:
  undefined method `add_grpup' for main:Object
# /Users/katsuki/.rvm/gems/ruby-2.4.1/gems/docile-1.3.1/lib/docile/fallback_context_proxy.rb:55:in `block in initialize'
# /Users/katsuki/.rvm/gems/ruby-2.4.1/gems/docile-1.3.1/lib/docile/fallback_context_proxy.rb:84:in `method_missing'
# ./spec/rails_helper.rb:9:in `block in <top (required)>'
# /Users/katsuki/.rvm/gems/ruby-2.4.1/gems/docile-1.3.1/lib/docile/execution.rb:26:in `instance_exec'
# /Users/katsuki/.rvm/gems/ruby-2.4.1/gems/docile-1.3.1/lib/docile/execution.rb:26:in `exec_in_proxy_context'
# /Users/katsuki/.rvm/gems/ruby-2.4.1/gems/docile-1.3.1/lib/docile.rb:43:in `dsl_eval'

# /Users/katsuki/.rvm/gems/ruby-2.4.1/gems/simplecov-0.16.1/lib/simplecov/configuration.rb:164:in `configure'
# /Users/katsuki/.rvm/gems/ruby-2.4.1/gems/simplecov-0.16.1/lib/simplecov.rb:49:in `start'
# ./spec/rails_helper.rb:6:in `<top (required)>'
# ./spec/requests/api/v1/posts_controller_spec.rb:1:in `require'
# ./spec/requests/api/v1/posts_controller_spec.rb:1:in `<top (required)>'
Linter
Severity  Provider  Description Line
00config/database.yml0002:22Prettier
LFUTF-8YAML
dev0 files1 update
# /Users/katsuki/.rvm/gems/ruby-2.4.1/gems/docile-1.3.1/lib/docile.rb:43:in `dsl_eval'
# /Users/katsuki/.rvm/gems/ruby-2.4.1/gems/simplecov-0.16.1/lib/simplecov/configuration.rb:164:in `configure'
# /Users/katsuki/.rvm/gems/ruby-2.4.1/gems/simplecov-0.16.1/lib/simplecov.rb:49:in `start'
# ./spec/rails_helper.rb:6:in `<top (required)>'
# ./spec/requests/api/v1/posts_controller_spec.rb:1:in `require'
# ./spec/requests/api/v1/posts_controller_spec.rb:1:in `<top (required)>'
No examples found.

An error occurred in a `before(:suite)` hook.
Failure/Error: DatabaseCleaner.clean_with(:truncation)

NameError:
  uninitialized constant DatabaseCleaner
# ./spec/spec_helper.rb:5:in `block (2 levels) in <top (required)>'
```

**Comment by K-Sato1995** [comment]
Solved
